name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '*.java'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
  pull_request:
    branches:
      - master
    paths:
      - '*.java'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew clean shadowJar

      - name: Select jar
        run: |
          cd guizhanlib-all/build/libs
          echo "FILE=$(ls | grep jar)" >> $GITHUB_ENV

      - name: Publish to repo
        run: ./gradlew publish
        env:
          MAVEN_ACCOUNT: '${{ secrets.MAVEN_ACCOUNT }}'
          MAVEN_PASSWORD: '${{ secrets.MAVEN_PASSWORD }}'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}
          path: guizhanlib-all/build/libs/${{ env.FILE }}
